
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class AppMenu
{

    public AppMenu()
    {

        this.Menus = new HashSet<Menu>();

    }


    public int AppId { get; set; }

    public string AppName { get; set; }

    public string Path { get; set; }

    public string Display { get; set; }

    public int SortOrder { get; set; }



    public virtual ICollection<Menu> Menus { get; set; }

}

}
