
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class EmailRecipient
{

    public string EReportId { get; set; }

    public string RecipientId { get; set; }

    public string AddedBy { get; set; }

    public Nullable<System.DateTime> DateStamp { get; set; }

}

}
