
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class EmailReport
{

    public string EReportId { get; set; }

    public string ReportDesc { get; set; }

    public byte SortOrder { get; set; }

    public byte ReportOrder { get; set; }

    public string GlobalSPName { get; set; }

    public string LocalSPName { get; set; }

    public string ReportID { get; set; }

    public string EMailSubject { get; set; }

    public string EMailBody { get; set; }

    public string AttachRpt { get; set; }

    public bool IsActive { get; set; }

    public string Excel { get; set; }

    public string PDF { get; set; }

    public string ConnectionString { get; set; }

    public string Hourly { get; set; }

}

}
