
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class ExecuteSP
{

    public string SpId { get; set; }

    public string DisplayName { get; set; }

    public string SpName { get; set; }

    public Nullable<int> AppID { get; set; }

    public string DBInstance { get; set; }

    public int Active { get; set; }

    public string UserDepts { get; set; }

    public string ReportType { get; set; }

    public string MultiSheet { get; set; }

    public string SheetNames { get; set; }

}

}
