

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class LinkHubDbEntities : DbContext
{
    public LinkHubDbEntities()
        : base("name=LinkHubDbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_Category> tbl_Category { get; set; }

    public virtual DbSet<tbl_Url> tbl_Url { get; set; }

    public virtual DbSet<tbl_User> tbl_User { get; set; }

    public virtual DbSet<AppMenu> AppMenus { get; set; }

    public virtual DbSet<Menu> Menus { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserAccess> UserAccesses { get; set; }

    public virtual DbSet<AgeGroup> AgeGroups { get; set; }

    public virtual DbSet<Person> People { get; set; }

}

}

