
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class Menu
{

    public int AppID { get; set; }

    public int MenuId { get; set; }

    public string MenuName { get; set; }

    public Nullable<int> BaseParentId { get; set; }

    public Nullable<int> ImmParentId { get; set; }

    public string Access { get; set; }

    public string Path { get; set; }

    public string Display { get; set; }

    public string EndNode { get; set; }



    public virtual AppMenu AppMenu { get; set; }

}

}
