
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class Report
{

    public string ReportID { get; set; }

    public string ReportName { get; set; }

    public Nullable<byte> ReportOrder { get; set; }

    public byte IsSubReport { get; set; }

    public byte ParamCount { get; set; }

    public byte FormulaCount { get; set; }

    public string BindTableName { get; set; }

    public string SPName { get; set; }

    public string ConnectionString { get; set; }

    public string OutputPDFName { get; set; }

}

}
