
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BOL
{

using System;
    using System.Collections.Generic;
    
public partial class ReportMaster
{

    public string RptID { get; set; }

    public string RptGroup { get; set; }

    public string RptName { get; set; }

    public string RptFileName { get; set; }

    public string RptFileNamePattern { get; set; }

    public string RptDesc { get; set; }

    public string SPName { get; set; }

    public string DBInstance { get; set; }

    public bool IsActive { get; set; }

    public bool IsFileTemplate { get; set; }

    public string TemplateFilename { get; set; }

    public Nullable<short> ConnectionTimeout { get; set; }

}

}
