//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccess
    {
        public int AppId { get; set; }
        public int MenuId { get; set; }
        public string UserId { get; set; }
        public string AccessRights { get; set; }
        public System.DateTime DateStamp { get; set; }
    }
}
